// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsCEXJPxGJfkGQ3xaq8ya-3ob1oJxT9es',
    appId: '1:807237372321:web:288ec28f2cc7ea0da4a3e0',
    messagingSenderId: '807237372321',
    projectId: 'uniattend-3404a',
    authDomain: 'uniattend-3404a.firebaseapp.com',
    storageBucket: 'uniattend-3404a.firebasestorage.app',
    measurementId: 'G-79GF5Z703F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWtylNs5sKxc2rLq0VELu89Y-IxTN_DwY',
    appId: '1:807237372321:android:f4d8336162226d9aa4a3e0',
    messagingSenderId: '807237372321',
    projectId: 'uniattend-3404a',
    storageBucket: 'uniattend-3404a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJczkxBP8uLNiKu4nixNi43sF-dJDGubI',
    appId: '1:807237372321:ios:bc3d573520c84f31a4a3e0',
    messagingSenderId: '807237372321',
    projectId: 'uniattend-3404a',
    storageBucket: 'uniattend-3404a.firebasestorage.app',
    iosBundleId: 'com.example.universityAttendanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJczkxBP8uLNiKu4nixNi43sF-dJDGubI',
    appId: '1:807237372321:ios:bc3d573520c84f31a4a3e0',
    messagingSenderId: '807237372321',
    projectId: 'uniattend-3404a',
    storageBucket: 'uniattend-3404a.firebasestorage.app',
    iosBundleId: 'com.example.universityAttendanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDsCEXJPxGJfkGQ3xaq8ya-3ob1oJxT9es',
    appId: '1:807237372321:web:5760525247a4e3c8a4a3e0',
    messagingSenderId: '807237372321',
    projectId: 'uniattend-3404a',
    authDomain: 'uniattend-3404a.firebaseapp.com',
    storageBucket: 'uniattend-3404a.firebasestorage.app',
    measurementId: 'G-CFCDYPRXVC',
  );
}
